config/routes.rb
Rails.application.routes.draw do
  
  resources :game_data

  resources :game_infos

  get 'parse_utilities/getLottory'

  resources :paperclip_images
  get 'paperclip_images/:id/download' , to: "paperclip_images#download" , :as => :download
  
  get 'profiles/show'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"}
  
  devise_scope :user do
    get "register" , to: "devise/registrations#new", as: :register
    get "login" , to: "devise/sessions#new", as: :login
    get "logout" , to: "devise/sessions#destroy", as: :logout
  end

  resources :statuses
  root to: 'statuses#index'

  get "feed/:id", to: "profiles#show", as: :feed

end

app/models/paperclip_image.rb
class PaperclipImage < ActiveRecord::Base
	has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/controllers/paperclip_images_controller.rb
class PaperclipImagesController < ApplicationController
  before_action :set_paperclip_image, only: [:show, :edit, :update, :destroy, :download]

  respond_to :html

  def index
    @paperclip_images = PaperclipImage.all
    respond_with(@paperclip_images)
  end

  def show
    respond_with(@paperclip_image)
  end

  def new
    @paperclip_image = PaperclipImage.new
    respond_with(@paperclip_image)
  end

  def edit
  end

  def create
    @paperclip_image = PaperclipImage.new(paperclip_image_params)
    @paperclip_image.save
    respond_with(@paperclip_image)
  end

  def update
    @paperclip_image.update(paperclip_image_params)
    respond_with(@paperclip_image)
  end

  def destroy
    @paperclip_image.destroy
    respond_with(@paperclip_image)
  end

  def download
    send_file @paperclip_image.picture.path(:original),
              :filename => @paperclip_image.picture_file_name,
              :type => @paperclip_image.picture_content_type,
              :disposition => 'attachment'
  end

  private
    def set_paperclip_image
      @paperclip_image = PaperclipImage.find(params[:id])
    end


    def paperclip_image_params
      params.require(:paperclip_image).permit(:picture)
    end
end

app/helpers/paperclip_images_helper.rb
module PaperclipImagesHelper
end

app/views/paperclip_images/_form.html.erb
<%= simple_form_for(@paperclip_image  , html: { :multipart => true })  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-group">
	  <%= f.label :picture %>
	  <%= f.file_field :picture , html: {class: 'form-control'} %>
    <% if f.object.picture? %>
      <br/>
      <%= image_tag(f.object.picture.url(:thumb)) %> <br/>
      <em>Currently uploaded image</em>
      <br/>
    <% end %>
  </div>



  <div class="form-actions">
    <%= f.button :submit, 'Save' , class: "btn btn-primary" %>
  </div>
<% end %>

app/views/paperclip_images/edit.html.erb
<h1>Editing paperclip_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @paperclip_image %> |
<%= link_to 'Back', paperclip_images_path %>

app/views/paperclip_images/index.html.erb
<h1>Listing paperclip_images</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paperclip_images.each do |paperclip_image| %>
      <tr>
        <td><%= link_to image_tag(paperclip_image.picture.url(:thumb), class: "img-thumbnail"), paperclip_image %></td>
        <td><%= link_to 'Download', download_path(paperclip_image) %>| </td> 
        <td><%= link_to 'Edit', edit_paperclip_image_path(paperclip_image) %>| </td>
        <td><%= link_to 'Destroy', paperclip_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Paperclip image', new_paperclip_image_path %>

app/views/paperclip_images/new.html.erb
<h1>New paperclip_image</h1>

<%= render 'form' %>

<%= link_to 'Back', paperclip_images_path %>

app/views/paperclip_images/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @paperclip_image.picture.url(:medium) , class: "img-thumbnail"%>

<%= link_to 'Edit', edit_paperclip_image_path(@paperclip_image) %> |
<%= link_to 'Back', paperclip_images_path %>