config/routes.rb
Rails.application.routes.draw do
  
  resources :game_data

  resources :game_infos

  get 'parse_utilities/getLottory'

  resources :paperclip_images
  get 'paperclip_images/:id/download' , to: "paperclip_images#download" , :as => :download
  
  get 'profiles/show'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"}
  
  devise_scope :user do
    get "register" , to: "devise/registrations#new", as: :register
    get "login" , to: "devise/sessions#new", as: :login
    get "logout" , to: "devise/sessions#destroy", as: :logout
  end

  resources :statuses
  root to: 'statuses#index'

  get "feed/:id", to: "profiles#show", as: :feed

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<a href="#" class="navbar-brand">Nate blog</a>
			<ul class="nav navbar-nav">
				<li><%= link_to "All Statuses", statuses_path %></li>
				<li><%= link_to "Upload Pictures", paperclip_images_path %></li>
				<li><%= link_to "Lottory Number", parse_utilities_getLottory_path %></li>
				<li><%= link_to "Game Info", game_infos_path %></li>
			</ul>

			<ul class="nav navbar-nav pull-right">
			<% if user_signed_in? %>
				<% unless current_user[:full_name].nil? %>
					<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
				<% end %>
				<% unless current_user[:email].nil? %>
					<li><%= link_to current_user.email, edit_user_registration_path %></li>	
				<% end %>
				<li><%= link_to "Log Out", logout_path  %></li>
			<% else %>
				<li><%= link_to "Register", register_path %></li>
				<li><%= link_to "Login", login_path %></li>
			<% end %>
			</ul>

		</div>
	</nav>


	<div class="container">
		<% flash.each do |type, message| %>
			<div class="alert <%= flash_class type %>">
				<button class="close" data-dismiss="alert">x</button>
				<%= message %>
			</div>
		<% end %>
	<%= yield %>
	</div>

</body>
</html>