config/routes.rb
Rails.application.routes.draw do
  
  resources :game_data

  resources :game_infos

  get 'parse_utilities/getLottory'

  resources :paperclip_images
  get 'paperclip_images/:id/download' , to: "paperclip_images#download" , :as => :download
  
  get 'profiles/show'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"}
  
  devise_scope :user do
    get "register" , to: "devise/registrations#new", as: :register
    get "login" , to: "devise/sessions#new", as: :login
    get "logout" , to: "devise/sessions#destroy", as: :logout
  end

  resources :statuses
  root to: 'statuses#index'

  get "feed/:id", to: "profiles#show", as: :feed

end

app/models/game_info.rb
class GameInfo < ActiveRecord::Base
	has_many :game_datum

	def getComputeGameMoney(tmpArray)
		resultArray = [0,0,0,0]

		#自摸
		if tmpArray[0] != 0 && tmpArray[1] != 0 && tmpArray[2] != 0 && tmpArray[3] != 0 
			(0..3).each do |i|
				if tmpArray[i] > 0
					resultArray[i] = base_pay * 3 + acc_pay*tmpArray[i]
				else
					resultArray[i] = base_pay * -1 + acc_pay*tmpArray[i]
				end
			end

		else
			(0..3).each do |i|
				if tmpArray[i] > 0
					resultArray[i] = base_pay * 1 + acc_pay*tmpArray[i]
				elsif tmpArray[i] == 0
					resultArray[i] == 0
				else
					resultArray[i] = base_pay * -1 + acc_pay*tmpArray[i]
				end
			end
		end

		return resultArray
	end

end

app/controllers/game_infos_controller.rb
class GameInfosController < ApplicationController
  before_action :set_game_info, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @game_infos = GameInfo.all
    respond_with(@game_infos)
  end

  def show
    respond_with(@game_info)
  end

  def new
    @game_info = GameInfo.new
    respond_with(@game_info)
  end

  def edit
  end

  def create
    @game_info = GameInfo.new(game_info_params)
    @game_info.save
    respond_with(@game_info)
  end

  def update
    @game_info.update(game_info_params)
    respond_with(@game_info)
  end

  def destroy
    @game_info.destroy
    respond_with(@game_info)
  end

  private
    def set_game_info
      @game_info = GameInfo.find(params[:id])
    end

    def game_info_params
      params.require(:game_info).permit(:info, :name1, :name2, :name3, :name4, :base_pay, :acc_pay)
    end
end

app/helpers/game_infos_helper.rb
module GameInfosHelper
end

app/views/game_infos/_form.html.erb
<%= simple_form_for(@game_info) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :info %>
    <%= f.input :name1 %>
    <%= f.input :name2 %>
    <%= f.input :name3 %>
    <%= f.input :name4 %>
    <%= f.input :base_pay %>
    <%= f.input :acc_pay %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/game_infos/edit.html.erb
<h1>Editing game_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_info %> |
<%= link_to 'Back', game_infos_path %>

app/views/game_infos/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Info</th>
      <th>Name1</th>
      <th>Name2</th>
      <th>Name3</th>
      <th>Name4</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_infos.each do |game_info| %>
      <tr>
        <td><%= game_info.info %></td>
        <td><%= game_info.name1 %></td>
        <td><%= game_info.name2 %></td>
        <td><%= game_info.name3 %></td>
        <td><%= game_info.name4 %></td>
        <td><%= link_to 'Show', game_info %></td>
        <td><%= link_to 'Edit', edit_game_info_path(game_info) %></td>
        <td><%= link_to 'Destroy', game_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game info', new_game_info_path , class: "btn btn-success"%>

app/views/game_infos/new.html.erb
<h1>New game_info</h1>

<%= render 'form' %>

<%= link_to 'Back', game_infos_path %>

app/views/game_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p class="gameInfo" data-acc="<%= @game_info.acc_pay %>"  data-base="<%= @game_info.base_pay %>"  >
  <strong>Game Info:<%= @game_info.info %> </strong>
  <button class="gameInfoBtn" > 詳細資料 </button>
  <p class="payInfo"></p>
</p>

<table class="table">
  <thead>
    <tr>
      <td></td>
      <td><%= @game_info.name1 %></td>
      <td><%= @game_info.name2 %></td>
      <td><%= @game_info.name3 %></td>
      <td><%= @game_info.name4 %></td>
    </tr> 
  </thead>
  <tbody>
    <% counter = 0 %>
    <% sumArray = [0,0,0,0] %>
    <% sumMoneyArray = [0,0,0,0] %>
    
    <% @game_info.game_datum.each do |datum| %>
        <% counter += 1 %>
        <% curArray = [datum.money1,datum.money2,datum.money3,datum.money4] %>
        <% curMoneyArray = @game_info.getComputeGameMoney(curArray) %>
        <tr>
          <td>Round<%= counter %></td>
          <% (0..3).each do |i| %>
            <td><%= curArray[i].to_s + "台:" + curMoneyArray[i].to_s %></td>
          <% end %>
        </tr> 

        <% (0..3).each do |i| %>
          <% sumMoneyArray[i] += curMoneyArray[i] %>
        <% end %>
    <% end %>

    <tr>
      <td>Balance </td>
      <td><%= sumMoneyArray[0] %></td>
      <td><%= sumMoneyArray[1] %></td>
      <td><%= sumMoneyArray[2] %></td>
      <td><%= sumMoneyArray[3] %></td>
    </tr> 
  </tbody>
</table>

  <div id="form">
    <%= render :partial => "game_data/form", :locals => {:game_datum => GameDatum.new, :game_info_id => @game_info.id } %>
  </div>
<%= link_to 'Edit Game Info', edit_game_info_path(@game_info) , class: "btn btn-default"  %>
<%= link_to 'Back', game_infos_path , class: "btn btn-default" %>